% +TEST
% 
%   Contents file for +TEST and its subfolders.
%
%   +TEST
%   groupstats.test.generateTestData         - Generate data for unit tests, demos, and scripts
%
%   +TEST/+FIXTURES
%   groupstats.test.fixtures.InvisibleFigure - Open an invisible figure for the duration of a test
%
%   This file was generated by updatecontents.m on 17 Aug 2026 at 00:11:32.
