% +TEST
% 
%   Contents file for +TEST and its subfolders.
%   
%   +TEST
%   groupstats.test.generateTestData - Generate test data
%   groupstats.test.runtests         - Run unit tests
%    
%   This file was generated by updatecontents.m on 14 Sep 2023 at 15:35:58.
