% +GROUPSTATS
% 
%   Contents file for +GROUPSTATS and its subfolders.
%   
%   +GROUPSTATS
%   groupstats.boxchartxdata                 - Retrieve x-axis data for boxcharts in handle H
%   groupstats.dropcats                      - Remove categories that are not present in a table variable
%   groupstats.groupbayes                    - Compute group-wise bayes probabilities
%   groupstats.grouppercent                  - Compute group-wise frequencies (percents) including groupsets
%   groupstats.groupselect                   - Select rows of table by variable name and group members
%   groupstats.groupstats                    - Comput group-wise statistics
%   groupstats.prepareTableGroups            - Prepare group data in table
%   groupstats.testnamespace                 - Test namespace access
%   
%   +GROUPSTATS/+INTERNAL
%   groupstats.internal.filelist             - List all files in folder and (optionally) subfolders
%   groupstats.internal.getversion           - Read version.txt in the toolbox root directory
%   groupstats.internal.installpath          - Get toolbox installation path from user preferences group
%   groupstats.internal.isoctave             - Determine if the environment is Octave
%   groupstats.internal.makecontents         - Make contents.m for each toolbox folder including packages
%   groupstats.internal.projectpath          - Return the full path to the top-level project directory
%   groupstats.internal.replacePackagePrefix - Replace namespace package prefix in function files
%   groupstats.internal.updatecontents       - Create a Contents.m file including subdirectories
%   groupstats.internal.withcd               - Temporarily cd to a directory
%   
%   +GROUPSTATS/+TEST
%   groupstats.test.generateTestData         - Generate test data
%   groupstats.test.runtests                 - Run unit tests
%   
%   +GROUPSTATS/PRIVATE
%   groupstats/private.isvariable            - Determine if VARNAME is a variable in table T
%   groupstats/private.settablevarnames      - Set table variable names
%   groupstats/private.withwarnoff           - Temporarily disable warnings
%    
%   This file was generated by updatecontents.m on 14 Sep 2023 at 15:35:58.
