% +NAMELISTS
% 
%   Contents file for +NAMELISTS and its subfolders.
%
%   +NAMELISTS
%   groupstats.namelists.centralstatistic  - Valid values for a method option that summarizes a group
%   groupstats.namelists.legendorientation - Valid values for a LegendOrientation option
%   groupstats.namelists.legendvisibility  - Valid values for a Legend option
%   groupstats.namelists.mustBeMemberOf    - Validate a value against a named list in this package
%   groupstats.namelists.populationoption  - Valid values for the groupbayes Population option
%   groupstats.namelists.sortdatavar       - Data arguments a sort order can read
%   groupstats.namelists.sortdirection     - Valid sort directions
%   groupstats.namelists.sortgroupvar      - Grouping arguments a sort order can follow
%   groupstats.namelists.sortorder         - Valid values for a SortBy option that can also skip sorting
%   groupstats.namelists.testtail          - Valid values for the tail of a rank test
%
%   This file was generated by updatecontents.m on 16 Aug 2026 at 15:17:23.
