% +FIXTURES
% 
%   Contents file for +FIXTURES and its subfolders.
%
%   +FIXTURES
%   groupstats.test.fixtures.InvisibleFigure - Open an invisible figure for the duration of a test
%
%   This file was generated by updatecontents.m on 16 Aug 2026 at 15:17:25.
