% +FIXTURES
% 
%   Contents file for +FIXTURES and its subfolders.
%
%   +FIXTURES
%   groupstats.test.fixtures.InvisibleFigure - Open an invisible figure for the duration of a test
%
%   This file was generated by updatecontents.m on 05 Sep 2026 at 23:45:18.
