% +INTERNAL
% 
%   Contents file for +INTERNAL and its subfolders.
%
%   +INTERNAL
%   groupstats.internal.buildpath                  - Build full path to toolbox folder or file
%   groupstats.internal.checkdependencies          - Report functions groupstats needs but does not ship
%   groupstats.internal.docpath                    - Return the path to a toolbox help page
%   groupstats.internal.installRequiredFiles       - Install required files from Github
%   groupstats.internal.makecontents               - Make contents.m for each folder including package folders
%   groupstats.internal.privatefunction            - Return handle(s) to private functions in toolbox
%   groupstats.internal.releaseoptions             - Build the packaging options a release uses
%   groupstats.internal.replacePackagePrefix       - Replace namespace package prefix in function files
%   groupstats.internal.runtests                   - Run all tests in the test suite
%   groupstats.internal.version                    - Read version.txt in the toolbox root directory
%
%   +INTERNAL/PRIVATE
%   groupstats.internal/private.backupfile         - Create a backup file name or folder name and (optionally) a copy
%   groupstats.internal/private.cellmap            - Apply function to cell-array
%   groupstats.internal/private.convertlivescripts - Convert live script to m-files
%   groupstats.internal/private.getcontents        - Get the contents of a specified directory
%   groupstats.internal/private.getRequiredFiles   - Retrieve requirements for MATLAB functions or toolboxes
%   groupstats.internal/private.installpath        - Return toolbox installation path from user preferences group
%   groupstats.internal/private.isoctave           - Return true if the environment is Octave
%   groupstats.internal/private.listfiles          - List all files in folder and (optionally) subfolders
%   groupstats.internal/private.listfolders        - Return a list of folders under a top-level directory
%   groupstats.internal/private.mpackagefolders    - List all package and sub-package folders in folder
%   groupstats.internal/private.mpackagename       - Return the package namespace name
%   groupstats.internal/private.projectpath        - Return the full path to the top-level project directory
%   groupstats.internal/private.rmdotfolders       - Remove dot folders from directory list
%   groupstats.internal/private.toolboxpath        - Return toolbox basepath
%   groupstats.internal/private.updatecontents     - Create a Contents.m file including subdirectories
%   groupstats.internal/private.withcd             - Temporarily cd to a directory
%
%   This file was generated by updatecontents.m on 16 Aug 2026 at 15:17:21.
