% +INTERNAL
% 
%   Contents file for +INTERNAL and its subfolders.
%   
%   +INTERNAL
%   groupstats.internal.filelist             - List all files in folder and (optionally) subfolders
%   groupstats.internal.getversion           - Read version.txt in the toolbox root directory
%   groupstats.internal.installpath          - Get toolbox installation path from user preferences group
%   groupstats.internal.isoctave             - Determine if the environment is Octave
%   groupstats.internal.makecontents         - Make contents.m for each toolbox folder including packages
%   groupstats.internal.projectpath          - Return the full path to the top-level project directory
%   groupstats.internal.replacePackagePrefix - Replace namespace package prefix in function files
%   groupstats.internal.updatecontents       - Create a Contents.m file including subdirectories
%   groupstats.internal.withcd               - Temporarily cd to a directory
%    
%   This file was generated by updatecontents.m on 14 Sep 2023 at 15:35:58.
