% +INTERNAL
% 
%   Contents file for +INTERNAL and its subfolders.
%
%   +INTERNAL
%   groupstats.internal.assertpackagedversion      - Error unless a packaged toolbox carries the version
%   groupstats.internal.buildpath                  - Build full path to toolbox folder or file
%   groupstats.internal.checkdependencies          - Report files groupstats needs but does not ship
%   groupstats.internal.demolist                   - The demo files makedocs publishes
%   groupstats.internal.docpath                    - Return the path to a toolbox help page
%   groupstats.internal.installRequiredFiles       - Install required files from GitHub or a local checkout
%   groupstats.internal.makecontents               - Make contents.m for each folder including package folders
%   groupstats.internal.makedocs                   - Publish the toolbox documentation as html files
%   groupstats.internal.privatefunction            - Return handle(s) to private functions in toolbox
%   groupstats.internal.releaseoptions             - Build the packaging options a release uses
%   groupstats.internal.replacePackagePrefix       - Replace namespace package prefix in function files
%   groupstats.internal.runtests                   - Run all tests in the test suite
%   groupstats.internal.tablecompletions           - Generate completions from table variables
%   groupstats.internal.vendordependencies         - Copy the files a toolbox calls from a local checkout
%   groupstats.internal.vendoredfiles              - Return the vendored copies listed in vendored.txt
%   groupstats.internal.version                    - Read version.txt in the toolbox root directory
%
%   +INTERNAL/PRIVATE
%   groupstats.internal/private.arraymap           - Apply a function to an array, returning a cell array of results
%   groupstats.internal/private.backupfile         - Create a backup file name or folder name and (optionally) a copy
%   groupstats.internal/private.cat2double         - Convert categorical data to double
%   groupstats.internal/private.cellmap            - Apply function to cell-array
%   groupstats.internal/private.convertlivescripts - Convert live script to m-files
%   groupstats.internal/private.getcontents        - Get the contents of a specified directory
%   groupstats.internal/private.getRequiredFiles   - Retrieve requirements for MATLAB functions or toolboxes
%   groupstats.internal/private.installpath        - Return toolbox installation path from user preferences group
%   groupstats.internal/private.islogicalscalar
%   groupstats.internal/private.isoctave           - Return true if the environment is Octave
%   groupstats.internal/private.isscalartext       - Return true if input is scalar text
%   groupstats.internal/private.listfiles          - List all files in folder and (optionally) subfolders
%   groupstats.internal/private.listfolders        - Return a list of folders under a top-level directory
%   groupstats.internal/private.mpackagefolders    - List all package and sub-package folders in folder
%   groupstats.internal/private.mpackagename       - Return the package namespace name
%   groupstats.internal/private.projectpath        - Return the full path to the top-level project directory
%   groupstats.internal/private.rmdotfolders       - Remove dot folders from directory list
%   groupstats.internal/private.tempfile           - Get a temporary file name, or full path to temporary file name
%   groupstats.internal/private.toolboxpath        - Return toolbox basepath
%   groupstats.internal/private.undersource        - True when FOLDER is ROOT or lies below it
%   groupstats.internal/private.updatecontents     - Create a Contents.m file including subdirectories
%   groupstats.internal/private.withcd             - Temporarily cd to a directory
%
%   This file was generated by updatecontents.m on 05 Sep 2026 at 23:45:18.
